---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions-patch-updates:
        update-types:
          - minor
          - patch
    labels:
      - dependencies
      - github-actions
