name: example

# Running jobs in a container
# https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: node:alpine
      env:
        NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Show current shell interpreter
        run: ps

      - name: Show Alpine release details
        run: cat /etc/os-release

      - name: Show node version
        run: node --version

      - name: Show npm version
        run: npm --version

      - name: Show node environment
        run: echo $NODE_ENV

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test --if-present

      - name: Check format
        run: npm run format-check
