name: example

# Running jobs in a container
# https://docs.github.com/en/actions/using-jobs/running-jobs-in-a-container

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: node:alpine
      env:
        NODE_ENV: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Show current shell interpreter # note: should show `sh`, not `bash` cause we're running Alpine
        run: ps
        # run: ps | grep ' sh$' | grep -v grep | awk '{print $NF}'

      - name: Show Alpine release details
        run: cat /etc/os-release

      - name: Show node version
        run: node --version

      - name: Show npm version
        run: npm --version

      - name: Show node environment
        run: echo $NODE_ENV

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test --if-present

      - name: Show prettier version
        run: npm run prettier-version

      - name: Check format
        run: npm run format-check
